### ISSUE TITLE
Deletes the whole content of the file when minifying or prettifying

### ISSUE THREAD

**Issue by BlackSkorpio** [1000ch/atom-svgo#7] opened 2016-07-10 00:14 UTC
Running Atom 1.8.0+SVGO 2.12 on Win7

When trying to minify/prettifying a file either via the menu or CTRL+SHIFT+O SVGO deletes all content from the file.

**Comment by 1000ch** [comment] 2016-08-19 09:08
BTW, 

1. Occur without shortcut key (`package` menu)? 
2. Would you try installing `apm install svgo` alternatively?

**Comment by BlackSkorpio** [comment] 2016-08-19 11:40
1.  It happens no matter what option I choose to use to minify the file
2. Where should I run that command, tried in it the atom command palette to no avail

**Comment by rugk** [comment] 2016-08-20 15:47
I can reproduce this too, but only on my Windows installation with Atom 1.9.9. On Linux it works fine.

**Comment by BlackSkorpio** [comment] 2016-08-26 12:35
Issue is still there in v2.2.0, with Win7 Atom 1.9.9

**Comment by 1000ch** [comment] 2016-08-26 16:23
@BlackSkorpio 

> Where should I run that command, tried in it the atom command palette to no avail

Try in CLI such as `Terminal.app` or `iTerm.app`?

**Comment by BlackSkorpio** [comment] 2016-08-26 16:54
Thnx, figured it out...

That took me a step further.
But instead generates this error when trying to minify a svg
```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\node_modules\csso\lib\compressor\index.js:109

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
    at compress (C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\node_modules\csso\lib\compressor\index.js:109:74)
    at minify (C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\node_modules\csso\lib\index.js:80:9)
    at Object.minifyBlock (C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\node_modules\csso\lib\index.js:106:12)
    at Object.exports.fn (C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\plugins\minifyStyles.js:38:42)
    at C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\lib\svgo\plugins.js:59:45
    at Array.filter (native)
    at monkeys (C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\lib\svgo\plugins.js:46:39)
    at perItem (C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\lib\svgo\plugins.js:77:12)
    at C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\lib\svgo\plugins.js:18:24
    at Array.forEach (native)
    at module.exports (C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\lib\svgo\plugins.js:14:13)
    at C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\lib\svgo.js:63:17
    at Object.sax.onend (C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\lib\svgo\svg2js.js:156:13)
    at emit (C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\node_modules\sax\lib\sax.js:640:35)
    at end (C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\node_modules\sax\lib\sax.js:683:5)
    at Object.write (C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\node_modules\sax\lib\sax.js:991:14)
    at Object.SAXParser.close (C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\node_modules\sax\lib\sax.js:157:38)
    at module.exports (C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\lib\svgo\svg2js.js:169:28)
    at SVGO._optimizeOnce (C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\lib\svgo.js:56:5)
    at SVGO.optimize (C:\Users\user_name\.atom\packages\svgo\node_modules\svgo\lib\svgo.js:49:11)
    at minify (C:\Users\user_name\.atom\packages\svgo\index.js:20:21)
    at atom-workspace.<anonymous> (C:\Users\user_name\.atom\packages\svgo\index.js:28:60)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user_name\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\user_name\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\user_name\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\user_name\AppData\Local\atom\app-1.9.9\resources\app.asar\src\atom-environment.js:1104:28)
    at EventEmitter.outerCallback (C:\Users\user_name\AppData\Local\atom\app-1.9.9\resources\app.asar\src\application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
The error was thrown from the svgo package.
```

**Comment by BlackSkorpio** [comment] 2016-08-27 13:55
This error was also reported here #4 
My current SVGO version is: `2.4.0`

**Comment by rugk** [comment] 2016-08-27 14:07
So is `eval` the issue?

**Comment by BlackSkorpio** [comment] 2016-08-27 14:12
Thats the error it put out right now.

**Comment by Nargilia** [comment] 2016-09-02 00:17
same problem

**Comment by rugk** [comment] 2016-09-02 19:47
I don't know what [CSP](https://content-security-policy.com/) Atom uses and how you can influence this, but the error certainly is there somewhere.
The best way to fix this would probably be to get rid of any [eval things](https://scotthelme.co.uk/content-security-policy-an-introduction/#realworldlimitations).

**Comment by 1000ch** [comment] 2016-12-25 00:36
@BlackSkorpio @Nargilia @rugk Still occur?

**Comment by BlackSkorpio** [comment] 2016-12-25 01:04
Now we (I) get another error
![image](https://cloud.githubusercontent.com/assets/11587201/21469347/53f8e78c-ca46-11e6-9bb0-aa52e64c9238.png)

Good news it dont deletes all content, it's only refuses to minifying it :/

**Comment by 1000ch** [comment] 2017-03-07 00:34
@BlackSkorpio 
It seems to be fixed with newest version 🙏

**Closed by 1000ch** 2017-03-07 00:34 UTC
